"""Adjust model 0.0.1

Revision ID: 0c5012dd00cc
Revises: edaa33d9db49
Create Date: 2024-03-06 14:35:31.977818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5012dd00cc'
down_revision = 'edaa33d9db49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_sk', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.drop_column('description_sk')

    # ### end Alembic commands ###
