"""Introduce types of elements 0.0.3

Revision ID: 2d64290e61a1
Revises: a5a59e566aaf
Create Date: 2024-03-06 17:32:52.707746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d64290e61a1'
down_revision = 'a5a59e566aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.alter_column('element_type',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('GRIPPER', 'LINE_EQUIPMENT', 'FITTINGS_N_TUBES', 'FLOW_CONTROL_EQUIPMENT', 'MECHANICAL_N_AIR_OPERATED_VALVES', 'PNEUMATIC_ACTUATORS', 'PRESSURE_N_VACUUM_SWITCHES', 'PROCESS_TECHNOLOGY', 'ROTARY_ACTUATOR', 'SAFETY_PRESSURE_RELEASE_VALVES', 'SOLENOID_VALVES', 'VACUUM_EQUIPMENT', 'OTHER', name='elementtype'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.alter_column('element_type',
               existing_type=sa.Enum('GRIPPER', 'LINE_EQUIPMENT', 'FITTINGS_N_TUBES', 'FLOW_CONTROL_EQUIPMENT', 'MECHANICAL_N_AIR_OPERATED_VALVES', 'PNEUMATIC_ACTUATORS', 'PRESSURE_N_VACUUM_SWITCHES', 'PROCESS_TECHNOLOGY', 'ROTARY_ACTUATOR', 'SAFETY_PRESSURE_RELEASE_VALVES', 'SOLENOID_VALVES', 'VACUUM_EQUIPMENT', 'OTHER', name='elementtype'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
