"""Introduce schema 0.0.2

Revision ID: a5a59e566aaf
Revises: 0c5012dd00cc
Create Date: 2024-03-06 16:58:16.873689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a59e566aaf'
down_revision = '0c5012dd00cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('name_sk', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('name_ua', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('element_type', sa.Enum('TUBE', name='elementtype'), nullable=True))
        batch_op.add_column(sa.Column('description_ua', sa.String(length=500), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('description_ua')
        batch_op.drop_column('element_type')
        batch_op.drop_column('name_ua')
        batch_op.drop_column('name_sk')
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
