"""Add description_en column

Revision ID: edaa33d9db49
Revises: f00886c1cc56
Create Date: 2024-03-02 16:03:40.613457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaa33d9db49'
down_revision = 'f00886c1cc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_en', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.drop_column('description_en')

    # ### end Alembic commands ###
